# MkDocs configuration for the Porter Mixin Generator documentation site.
site_name: Porter Mixin Generator (Skeletor)
site_url: https://getporter.github.io/skeletor/ # Assuming this is the target URL
repo_url: https://github.com/getporter/skeletor/
edit_uri: edit/main/gh-pages-docs/ # Link to edit source files

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

# Define the navigation structure
nav:
  - Home: index.md
  # Add other pages as needed, e.g., linking to CONTRIBUTING.md

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Copyright (optional)
# copyright: Copyright &copy; The Porter Authors
