# GitHub Actions workflow for building and deploying the MkDocs site
# for the Porter Mixin Generator (skeletor) repo to GitHub Pages.
name: Deploy Generator Docs to GitHub Pages

on:
  release:
    types: [published] # Trigger only when a release is published
  push:
    branches:
      - main # Also deploy on push to main for latest docs (optional)
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read # Need read access to checkout the repository
  pages: write # Need write access to deploy to GitHub Pages
  id-token: write # Needed for GitHub Pages deployment action

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    # Environment block removed - deployment action handles context
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info used by mkdocs-material

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x # Use a recent Python 3 version

      - name: Install MkDocs and theme
        run: pip install mkdocs mkdocs-material

      # --- Prepare Documentation Source ---
      # Create a temporary directory for the site source
      - name: Create site source directory
        run: mkdir site_src

      # Copy necessary files into the source directory
      - name: Copy documentation files
        run: |
          cp README.md site_src/index.md # Use README as index
          # Add cp commands for any other markdown files (e.g., CONTRIBUTING.md)
          # cp CONTRIBUTING.md site_src/contributing.md

      # --- Build and Deploy ---
      - name: Build MkDocs site
        run: mkdocs build --config-file mkdocs.yml --site-dir _site --clean

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site' # Path to the built site directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
